name:  CI Actividad 10

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pages: write 

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://junalchowdhuryg.github.io/Actividades-CC3S2/Actividad-10/


    steps:
    # clonar repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    # configurar Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
      working-directory: Actividad-10

    # ejecutar flake8
    - name: Run flake8
      run: |
        flake8 . --output-file=flake8-report.txt --tee
      working-directory: Actividad-10
      continue-on-error: true

    # ejecutar  pruebas de cobertura
    - name: Run tests with coverage
      run: |
        pytest --cov=Actividad-10 --cov-report=html --cov-report=term-missing -v
      working-directory: Actividad-10

    # Verifica que htmlcov/ existe (debugging)
    - name: Check htmlcov folder
      run: |
        ls -la  Actividad-10/htmlcov/
        if [ ! -f  Actividad-10/htmlcov/index.html ]; then
          echo "Error: htmlcov/index.html not found"
          exit 1
        fi
    
    - name: Add .nojekyll file
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        touch Actividad-10/htmlcov/.nojekyll

    # subir informe cobertura como artefacto
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: Actividad-10/htmlcov/

    # configurar github page
    - name: Setup Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v5

    - name: Upload Pages artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: Actividad-10/htmlcov/

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}