name:  CI Actividad 10

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Actividad-10
    steps:
    # clonar repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    # configurar Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    # ejecutar flake8
    - name: Run flake8
      run: |
        flake8 . --output-file=flake8-report.txt --tee
      continue-on-error: true


    # ejecutar  pruebas de cobertura
    - name: Run tests with coverage
      run: |
        pytest --cov=pruebas_pytest --cov-report=html --cov-report=term-missing -v

    # subir informe cobertura como artefacto
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: Actividad-10/htmlcov/

    # configurar github page
    - name: Setup Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v5

    - name: Upload Pages artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: Actividad-10/htmlcov/

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}